cloudfoundry/docs-cf-cli

- use-cli-plugins.html.md.erb
> replaced links to point at cli.cloudfoundry.org pages

- use-cli-plugins.html.md.erb
Spaces, it is aligned to view code with any editor, including the web
page view (such as in the GitHub code). When use tabs, the view on the
page is chaos, and it is terrible to mix tabs and spaces.
> Replace the tab with 4 spaces

- install-go-cli.html.md.erb
The previously grouped instructions were only for Mac.
/cc @konklone
> create Linux installation instructions

- cf-help.html.md.erb
add descriptions for the `cf restart` and `cf restage` commands since the difference between the two is not clear to new users
> add description for restart and restage

- install-go-cli.html.md.erb
The simplest thing to do from other places is to link directly to the instructions for a given OS, eg https://docs.cloudfoundry.org/cf-cli/install-go-cli.html#windows
However when you do this, the user has to scroll up to see the link to download an installer, then they have to click through, then they have to know which version to download on a confusing page... even though the links on that page are not version-dependent.
This change puts the OS-specific download link right in the OS-specific instructions, making it very obvious what to do without sending the user through other pages and contexts.
> Deep-linked instructions now more self-contained

- use-cli-plugins.html.md.erb
6.7.0 was released 2.5 yrs ago, no need to mention. Also, not likely people reached this section if they didn't already have/know how to find the cf CLI?
> removed note on super old minimum cf CLI version for plugins

- use-cli-plugins.html.md.erb
added some whitespace as was in the original, but not clear what it's there for and how many are required
> updated that CLI now prompts to uninstall same-named plugin

- self-signed.html.md.erb
This option will only work on Linux. It allows users to set certificate via environment variable and does not require sudo rights.
> Add env variable alternatives to set certificate

- http-proxy.html.md.erb
Golang 1.9 adds support for SOCKS5 proxies from the https_proxy environment variable. The cf CLI now supports SOCKS5 proxies as well (except for cf ssh and cf logs)
[#152946000]
> Update documentation to include SOCKS5 proxy support

- install-go-cli.html.md.erb
Use HTTPS to fix APT update bug. 
[#155275176] (cloudfoundry/cli#1327)
> use https for debian repo

- http-proxy.html.md.erb
In version 6.38.0, the CLI now supports SOCKS5 proxies through the `v3-ssh` command. The docs should be updated when v6.38.0 is released.
> update docs for SOCKS5 implementation

- v7.html.md.erb
Flags should be optional. This is now an argument (the second argument),
not a flag. It continues to be required.
Relevant Style Guide: https://github.com/cloudfoundry/cli/wiki/CF-CLI-Style-Guide#args-vs-flags
Also, fixed sorting: `rename-buildpack` is before `restart-app-instance`
[#172617004]
Authored-by: Brian Cunnie <bcunnie@pivotal.io>
> V7: `*-network-policy`: no `--destination-app` flag

- v7.html.md.erb
Hi Docs Team. We are preparing to GA cf CLI version 7. We are trying to remove references to any beta tags left behind. This is one of 3 PRs. The others should be in docs-cf-admin, docs-dev-guide.
> update cli V7 docs for GA

- v7.html.md.erb
TCP routing was previously out of scope for v7 CLI work, but has been brought into scope
[#172748423](https://www.pivotaltracker.com/story/show/172748423)
> Remove lines indicating that TCP routing is not supported by the v7 CLI

- v7.html.md.erb
--random-route is now default in v7 so there's no need for the flag
> added `map-route` to the table of changes

- v7.html.md.erb
We are confident that the required version of CAPI (1.95.0) will be bundled in the next CF Deployment (v13.4.0 or v14.0.0).
Co-authored-by: Reid Mitchell <rmitchell@pivotal.io>
> Requirements for cf CLI v7

- index.html.md.erb
- install-go-cli.html.md.erb
This PR depends on this other PR: https://github.com/pivotal-cf/concourse-scripts-docs/pull/16 being merged and the pipeline running so that the cf7-help page exists on the 13.5 branch.
(https://github.com/cloudfoundry/docs-cf-cli/blob/master/cf7-help.html.md.erb)
> 13.5 v6 and v7 installation

- v7.html.md.erb
This column was removed in cf v7 because the API to get routes service was not complete at the time
> Document removal of service column from cf routes

- getting-started.html.md.erb
* The cf CLI now supports reporting the logging rate of an application. Update the `cf push` output to show this.
* The `--hostname` flag is no longer accepted by `cf push`. Describe use of `cf map-route` to add the route. An alternative would be to define the route in the manifest file.
* The existing wording implied that the cf CLI itself was sending syslog messages. This is not correct.
> Update cf push output to include log rate details

- v8.html.md.erb
The output of the command `cf service-key` changed in a breaking way. All JSON elements that were on the JSON root level with v6 and v7 are now with v8 underneath a single root element called `credentials`. This breaks automated parsing of the JSON and is worth mentioning.
> Point out cf service-key changes

- getting-started.html.md.erb
- v7.html.md.erb
This PR updates CAPI v2 docs links from `apidocs.cloudfoundry.org` to `v2-apidocs.cloudfoundry.org`.
The goal is to signal that v3 is the primary API, also a necessary step in eventually sunsetting v2.
~~The infrastructure hosting the app serving docs at apidocs.cloudfoundry.org is expected to go down imminently, so this change is needed to avoid dead links.~~
`apidocs.cloudfoundry.org` has been converted to a redirect to `v3-apidocs.cloudfoundry.org`, so this change is needed to avoid incorrect links
See capi-release PRs [#440](https://github.com/cloudfoundry/capi-release/pull/440) and [#441](https://github.com/cloudfoundry/capi-release/pull/441)
> Update CAPI v2 docs links to new subdomain

- install-go-cli.html.md.erb
`apt-key` is deprecated since quite a while in Debian/Ubuntu.
This PR updates the repo add steps for Ubuntu/Debian.
They are supported with Debian 9+ and Ubuntu 18.04+.
I also created an issue to update the cli wiki page: https://github.com/cloudfoundry/cli/issues/3210
> update ubuntu install steps

- install-go-cli.html.md.erb
@pspinrad I did screw up copying the right commands from my test system. Sorry!
Due the combination of two mistakes, it was still working for me.
The downloaded key first needs to be converted into the gpg format and then the correct file needs to be referenced.
I also updated: https://github.com/cloudfoundry/cli/issues/3210
> fix ubuntu cli install steps

- getting-started.html.md.erb
- use-cli-plugins.html.md.erb
We are planning on deprecating the cli.cloudfoundry.org reference docs since they are out of date and duplicative of the `--help` flag. This PR removes links to that site and instead points users at using the `--help` flag directly to learn more about a command.
Related: https://github.com/cloudfoundry/docs-book-cloudfoundry/pull/140
> Refer to --help flag instead of reference docs
